### ISSUE TITLE
Why not TOML?

### ISSUE THREAD

**Issue by sosodev** [jordanorelli/moon#11]
It would be nice to see the answer to this added to the WHY faq. It seems like moon is pretty similar to TOML, and I'd appreciate your insight. :)

**Comment by jordanorelli** [comment]
there are so, so many things I dislike about TOML.

The whole thing where it's literally just the dude's name plus and L for language is insanely grating to me. Sorry but when you get removed from a leadership post due to serial sexual harassment, I don't want to be reminded of you every time I configure a server.

Then there's the fact that it's called "obvious". Look, whether or not something is "obvious" is clearly a matter of experience. Something that's obvious for you may not be obvious to others, and to make a blanket statement that something is obvious is doubly condescending.

Then there's the format itself.

```
[servers]

  # Indentation (tabs and/or spaces) is allowed but not required
  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"
```

If you want to rename the parent object, you have to rename the key in all the child objects. Neat. 

Dotted keys don't make this any better. You can use them to avoid the square brackets if you find them spooky, but it's not at all clear why having two representations for the same thing is useful.

According to spec, these two things produce the same result:

```
foo = "bar"
"foo" = "bar"
```

These two things produce different results:
```
a.b = "c"
"a.b" = "c"
```

That's not obvious at all. `a.b = "c"` should produce a json equivalent of `{"a": {"b": "c"}}` but try to find an online TOML to JSON parser that lets you check out these differences. Here's three that don't:
http://toml-online-parser.ovonick.com/
https://toml-to-json.matiaskorhonen.fi/
https://toolkit.site/format.html

These are the top three highest-rankedTOML manipulation tools when searching on Google. If TOML was so obvious, would all of these tools be so easily broken? Just to drive that point home: even on Github, the website that Tom cofounded, the dotted keys examples are highlighted in red because the TOML parser on Github is broken. So obvious!

Of course, there's no reference implementation for TOML so nobody built one that uses the reference implementation, they just all use their own broken implementations. The implementations are broken because the specification is bonkers. If it was obvious, it would be easy to get right, but it's not.

```
[dog."tater.man"]
type.name = "pug"
```

^ That's apparently legal, but I have no idea why you would ever want such a thing. The only reason you'd want such a thing is if you were generating the file from a machine, but, doy, wasn't this supposed to be "for humans"? 

It's not at all clear why there are multiple ways to make a hash table, let alone _three_, because I haven't even bothered to get to the part where you can do `{a = "b"}`

> Multi-line basic strings are surrounded by three quotation marks on each side and allow newlines. A newline immediately following the opening delimiter will be trimmed.

So if you put a space after the opening `"""` you're adding both a space and a newline. The only safe way to read a TOML file is with your editor configured to show whitespace markers to avoid this. The closing `""""` doesn't perform any trim. Baffling and I'm sure that the way these things are interpreted varies widely from interpretation to interpretation.

Numeric lexemes are numbers in some contexts, strings in others.
`key = 1234` has `1234` the number, `1234 = key` has `1234` the string. 

There's a datetime type but it has five representations. Or is there a date type, a time type, and a datetime type?

Data types may not be mixed within arrays. What? Why? This is totally random. There's no type signifiers anywhere, so it's effectively dynamically typed, except for this one specific thing. `[1, 2.0]` is invalid? That's not at all obvious. I thought I was just showing up for "json with comments", now I need to have typed arrays everywhere in my application?

The array of tables part of the spec isn't even remotely obvious. One set of brackets, it's a table, two sets of brackets, it's an array of tables! Obvious!

TOML is what happens when you take every idea you have and put them all together without considering whether or not they coexist peaceably without acting weird together.

Besides, the thing doesn't even have backreferencing, which is the _one_ thing I want to have. I originally started this because I had very large JSON documents to deal with that had repetitive sub-structures that couldn't be simplified. TOML doesn't help with that in the slightest.

I didn't initially include it because I didn't want to recognize TOML as existing. TOML has way too many useless and redundant features, 

(fwiw I actually use HCL in prod, I never really finished this project.)

**Comment by sosodev** [comment]
Great write up. I didn't realize TOML was such a mess, but my configuration files haven't been very complex.

**Comment by jordanorelli** [comment]
heh, it's basically all garbage in theory. It's basically all fine in practice. See... here, for example: http://seriot.ch/parsing_json.php

json is complete garbage... in theory. In practice it's fine ... like ... most of the time. Use the garbage your friends use and you'll never be alone. Lots of people use TOML with success. I didn't include it in the FAQ because I knew my explanation would be much too rude.
